# docs.serverless.com
service: libtom-aws-lambda

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-2

functions:
  login:
    handler: lambda.account
    events:
      - http:
          path: /login
          method: post
          cors: true
  logout:
    handler: lambda.account
    events:
      - http:
          path: /logout
          method: post
          cors: true
  register:
    handler: lambda.account
    events:
      - http:
          path: /register
          method: put
          cors: true
  remove:
    handler: lambda.account
    events:
      - http:
          path: /remove/{account_id}
          method: delete
          cors: true
          request:
            parameters:
              paths:
                account_id: true
  update:
    handler: lambda.account
    events:
      - http:
          path: /update
          method: post
          cors: true
  reset:
    handler: lambda.account
    events:
      - http:
          path: /reset
          method: post
          cors: true
  session:
    handler: lambda.account
    events:
      - http:
          path: /session/{token}
          method: get
          cors: true
          request:
            parameters:
              paths:
                token: true
