# docs.serverless.com
service: aws-lambda-source

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-2

functions:
  books:
    handler: lambda.handler
    events:
      - http:
          path: /books
          method: get
          cors: true

  book:
    handler: lambda.handler
    events:
      - http:
          path: /book/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true

  authors:
    handler: lambda.handler
    events:
      - http:
          path: /authors
          method: get
          cors: true

  author:
    handler: lambda.handler
    events:
      - http:
          path: /author/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true

  version:
    handler: lambda.handler
    events:
      - http:
          path: /v1/version
          method: get
          cors: true

  echo:
    handler: lambda.handler
    events:
      - http:
          path: /v1/echo
          method: post
          cors: true
